openapi: 3.0.1
info:
  title: Memberships API
  description: API for managing memberships, including coverage and demographic information.
  version: 1.0.0
paths:
  /memberships:
    get:
      summary: Retrieve all memberships
      tags:
        - Memberships
      responses:
        '200':
          description: A list of memberships
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Membership'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /memberships/{id}:
    get:
      summary: Retrieve a specific membership by ID
      tags:
        - Memberships
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the membership to retrieve
      responses:
        '200':
          description: Membership details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Membership'
        '404':
          description: Membership not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    Membership:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the membership
        member_info:
          type: object
          properties:
            first_name:
              type: string
            last_name:
              type: string
            email:
              type: string
            date_of_birth:
              type: string
              format: date
              description: The date of birth of the member (YYYY-MM-DD)
            oscar_id:
              type: string
            family_role:
              type: string
              enum:
                - POLICY_HOLDER
                - SPOUSE
                - CHILD
                - WARD
        eligibility_info:
          type: object
          properties:
            effectuation_status:
              type: string
              enum:
                - UNKNOWN
                - EFFECTUATED
                - CANCELLED
                - TERMINATED
                - REINSTATED
                - UNEFFECTUATED
            coverage_start:
              type: string
              format: date
            coverage_end:
              type: string
              format: date
            payment_status:
              type: string
              enum:
                - UNKNOWN
                - NONE
                - PAID
                - UNPAID
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        code:
          type: integer
